# Generated by Django 5.2.13 on 2026-04-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                (
                    "short_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("click_count", models.IntegerField(default=0)),
            ],
        ),
    ]
